name: Weekly Menu OCR Update


on:
schedule:
# 매주 토/일 00:00 UTC (KST +9 → 오전 9시) 실행
- cron: '0 0 * * SAT,SUN'
workflow_dispatch: {}


jobs:
update-menu:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Install system deps (tesseract)
run: |
sudo apt-get update
sudo apt-get install -y tesseract-ocr tesseract-ocr-kor libtesseract-dev


- name: Setup Python
uses: actions/setup-python@v5
with:
python-version: '3.11'


- name: Install Python deps
run: |
python -m pip install --upgrade pip
pip install requests pillow pytesseract playwright
python -m playwright install --with-deps chromium


- name: Run updater
env:
GIST_ID: ${{ secrets.GIST_ID }}
GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
NAVER_IMAGE_URL: ${{ vars.NAVER_IMAGE_URL }} # 선택 (권장)
NAVER_PLACE_URL: ${{ vars.NAVER_PLACE_URL }} # 선택 (실험적)
run: |
python automation/run.py
